# Generated by Django 2.0.9 on 2021-10-21 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('house_no_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'buyer',
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('BUYER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.buyer')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='delivery_boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delboy_name', models.CharField(max_length=50)),
                ('house_no_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'delivery_boy',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('BUYER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.buyer')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('DELIVERY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.delivery_boy')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='order_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qunatity', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'order_sub',
            },
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('BUYER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.buyer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('ORDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.orders')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_rate', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('PRODUCT_CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_in', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.category')),
                ('LOGIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.login')),
            ],
            options={
                'db_table': 'shops',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='SHOP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.shops'),
        ),
        migrations.AddField(
            model_name='rating',
            name='USER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.buyer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='SHOP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.shops'),
        ),
        migrations.AddField(
            model_name='order_sub',
            name='ORDER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.orders'),
        ),
        migrations.AddField(
            model_name='order_sub',
            name='PRODUCT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.product'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='PRODUCT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.product'),
        ),
        migrations.AddField(
            model_name='delivery_boy',
            name='LOGIN_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.login'),
        ),
        migrations.AddField(
            model_name='cart',
            name='PRODUCT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.product'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='LOGIN_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.login'),
        ),
    ]
