# Generated by Django 2.0.9 on 2021-10-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='CATEGORY',
        ),
        migrations.AddField(
            model_name='shops',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
