# Generated by Django 2.0.9 on 2021-10-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20211022_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('DELBOY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.delivery_boy')),
                ('ORDER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.orders')),
            ],
        ),
    ]
