# Generated by Django 2.0.9 on 2021-10-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_order_assign'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order_assign',
            table='order_assign',
        ),
    ]
