# Generated by Django 2.0.9 on 2021-10-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_auto_20211023_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='buyer',
            name='post',
            field=models.CharField(default='', max_length=50),
        ),
    ]
