# Generated by Django 2.0.9 on 2021-10-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_auto_20211025_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('pin_no', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
    ]
