# Generated by Django 2.0.9 on 2021-11-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_1', models.CharField(max_length=50)),
                ('quantity_2', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('PRODUCT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.product')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
    ]
